import type { NextConfig } from "next";

const nextConfig: NextConfig = {
  reactCompiler: true,
  turbopack: {},
};

// The PWA layer (service worker registration, runtime caching, background sync
// and push handling) lives in /public/sw.js and is registered by
// <ServiceWorkerRegister />. It used to be generated by @ducanh2912/next-pwa,
// but that plugin hooks into webpack and this app builds with Turbopack, so it
// silently emitted nothing.
export default nextConfig;
